1..15
# Started on 01/09/15 00:13:11
# Starting class: TestTiti
TestTiti:setUp
some stuff test 1
not ok 1	TestTiti.test1_withFailure
    example_with_luaunit.lua:99: expected: 2, actual: 1
    stack traceback:
    	.\luaunit.lua:476: in function 'assertEquals'
    	example_with_luaunit.lua:99: in function 'TestTiti.test1_withFailure'
    	.\luaunit.lua:1432: in function <.\luaunit.lua:1432>
    	[C]: in function 'xpcall'
    	.\luaunit.lua:1432: in function 'protectedCall'
    	.\luaunit.lua:1489: in function 'execOneFunction'
    	.\luaunit.lua:1588: in function 'runSuiteByInstances'
    	.\luaunit.lua:1641: in function 'runSuiteByNames'
    	.\luaunit.lua:1717: in function 'runSuite'
    	example_with_luaunit.lua:140: in main chunk
    	[C]: in ?
TestTiti:tearDown
TestTiti:setUp
some stuff test 2
not ok 2	TestTiti.test2_withFailure
    example_with_luaunit.lua:108: expected: "bof"
    actual: "hop"
    stack traceback:
    	.\luaunit.lua:476: in function 'assertEquals'
    	example_with_luaunit.lua:108: in function 'TestTiti.test2_withFailure'
    	.\luaunit.lua:1432: in function <.\luaunit.lua:1432>
    	[C]: in function 'xpcall'
    	.\luaunit.lua:1432: in function 'protectedCall'
    	.\luaunit.lua:1489: in function 'execOneFunction'
    	.\luaunit.lua:1588: in function 'runSuiteByInstances'
    	.\luaunit.lua:1641: in function 'runSuiteByNames'
    	.\luaunit.lua:1717: in function 'runSuite'
    	example_with_luaunit.lua:140: in main chunk
    	[C]: in ?
TestTiti:tearDown
TestTiti:setUp
some stuff test 3
TestTiti:tearDown
ok     3	TestTiti.test3
# Starting class: TestToto
some stuff test 1
not ok 4	TestToto.test1_withFailure
    example_with_luaunit.lua:19: expected: 2, actual: 1
    stack traceback:
    	.\luaunit.lua:476: in function 'assertEquals'
    	example_with_luaunit.lua:19: in function 'TestToto.test1_withFailure'
    	.\luaunit.lua:1432: in function <.\luaunit.lua:1432>
    	[C]: in function 'xpcall'
    	.\luaunit.lua:1432: in function 'protectedCall'
    	.\luaunit.lua:1489: in function 'execOneFunction'
    	.\luaunit.lua:1588: in function 'runSuiteByInstances'
    	.\luaunit.lua:1641: in function 'runSuiteByNames'
    	.\luaunit.lua:1717: in function 'runSuite'
    	example_with_luaunit.lua:140: in main chunk
    	[C]: in ?
some stuff test 2
not ok 5	TestToto.test2_withFailure
    example_with_luaunit.lua:28: expected: "bof"
    actual: "hop"
    stack traceback:
    	.\luaunit.lua:476: in function 'assertEquals'
    	example_with_luaunit.lua:28: in function 'TestToto.test2_withFailure'
    	.\luaunit.lua:1432: in function <.\luaunit.lua:1432>
    	[C]: in function 'xpcall'
    	.\luaunit.lua:1432: in function 'protectedCall'
    	.\luaunit.lua:1489: in function 'execOneFunction'
    	.\luaunit.lua:1588: in function 'runSuiteByInstances'
    	.\luaunit.lua:1641: in function 'runSuiteByNames'
    	.\luaunit.lua:1717: in function 'runSuite'
    	example_with_luaunit.lua:140: in main chunk
    	[C]: in ?
some stuff test 3
ok     6	TestToto.test3
some stuff test 4
not ok 7	TestToto.test4
    example_with_luaunit.lua:41: Received the not expected value: 1
    stack traceback:
    	.\luaunit.lua:516: in function 'assertNotEquals'
    	example_with_luaunit.lua:41: in function 'TestToto.test4'
    	.\luaunit.lua:1432: in function <.\luaunit.lua:1432>
    	[C]: in function 'xpcall'
    	.\luaunit.lua:1432: in function 'protectedCall'
    	.\luaunit.lua:1489: in function 'execOneFunction'
    	.\luaunit.lua:1588: in function 'runSuiteByInstances'
    	.\luaunit.lua:1641: in function 'runSuiteByNames'
    	.\luaunit.lua:1717: in function 'runSuite'
    	example_with_luaunit.lua:140: in main chunk
    	[C]: in ?
some stuff test 5
not ok 8	TestToto.test5
    example_with_luaunit.lua:47: expected: false, actual: 1
    stack traceback:
    	.\luaunit.lua:452: in function 'assertFalse'
    	example_with_luaunit.lua:47: in function 'TestToto.test5'
    	.\luaunit.lua:1432: in function <.\luaunit.lua:1432>
    	[C]: in function 'xpcall'
    	.\luaunit.lua:1432: in function 'protectedCall'
    	.\luaunit.lua:1489: in function 'execOneFunction'
    	.\luaunit.lua:1588: in function 'runSuiteByInstances'
    	.\luaunit.lua:1641: in function 'runSuiteByNames'
    	.\luaunit.lua:1717: in function 'runSuite'
    	example_with_luaunit.lua:140: in main chunk
    	[C]: in ?
some stuff test 6
not ok 9	TestToto.test6
    example_with_luaunit.lua:52: expected: true, actual: false
    stack traceback:
    	.\luaunit.lua:446: in function 'assertTrue'
    	example_with_luaunit.lua:52: in function 'TestToto.test6'
    	.\luaunit.lua:1432: in function <.\luaunit.lua:1432>
    	[C]: in function 'xpcall'
    	.\luaunit.lua:1432: in function 'protectedCall'
    	.\luaunit.lua:1489: in function 'execOneFunction'
    	.\luaunit.lua:1588: in function 'runSuiteByInstances'
    	.\luaunit.lua:1641: in function 'runSuiteByNames'
    	.\luaunit.lua:1717: in function 'runSuite'
    	example_with_luaunit.lua:140: in main chunk
    	[C]: in ?
not ok 10	TestToto.test7
    example_with_luaunit.lua:58: expected: {1, 2, three=3}
    actual: {1, 2}
    stack traceback:
    	.\luaunit.lua:471: in function 'assertEquals'
    	example_with_luaunit.lua:58: in function 'TestToto.test7'
    	.\luaunit.lua:1432: in function <.\luaunit.lua:1432>
    	[C]: in function 'xpcall'
    	.\luaunit.lua:1432: in function 'protectedCall'
    	.\luaunit.lua:1489: in function 'execOneFunction'
    	.\luaunit.lua:1588: in function 'runSuiteByInstances'
    	.\luaunit.lua:1641: in function 'runSuiteByNames'
    	.\luaunit.lua:1717: in function 'runSuite'
    	example_with_luaunit.lua:140: in main chunk
    	[C]: in ?
not ok 11	TestToto.test8a
    example_with_luaunit.lua:76: Bouhouhoum error!
    stack traceback:
    	example_with_luaunit.lua:76: in function 'funcWithError'
    	example_with_luaunit.lua:63: in function 'TestToto.test8a'
    	.\luaunit.lua:1432: in function <.\luaunit.lua:1432>
    	[C]: in function 'xpcall'
    	.\luaunit.lua:1432: in function 'protectedCall'
    	.\luaunit.lua:1489: in function 'execOneFunction'
    	.\luaunit.lua:1588: in function 'runSuiteByInstances'
    	.\luaunit.lua:1641: in function 'runSuiteByNames'
    	.\luaunit.lua:1717: in function 'runSuite'
    	example_with_luaunit.lua:140: in main chunk
    	[C]: in ?
not ok 12	TestToto.test8b
    example_with_luaunit.lua:76: Bouhouhoum error!
    stack traceback:
    	example_with_luaunit.lua:76: in function 'funcWithError'
    	example_with_luaunit.lua:72: in function 'funcWithFuncWithError'
    	example_with_luaunit.lua:68: in function 'TestToto.test8b'
    	.\luaunit.lua:1432: in function <.\luaunit.lua:1432>
    	[C]: in function 'xpcall'
    	.\luaunit.lua:1432: in function 'protectedCall'
    	.\luaunit.lua:1489: in function 'execOneFunction'
    	.\luaunit.lua:1588: in function 'runSuiteByInstances'
    	.\luaunit.lua:1641: in function 'runSuiteByNames'
    	.\luaunit.lua:1717: in function 'runSuite'
    	example_with_luaunit.lua:140: in main chunk
    	[C]: in ?
not ok 13	test1_withFailure
    example_with_luaunit.lua:124: assertion failed!
    stack traceback:
    	example_with_luaunit.lua:124: in function 'test1_withFailure'
    	.\luaunit.lua:1434: in function <.\luaunit.lua:1434>
    	[C]: in function 'xpcall'
    	.\luaunit.lua:1434: in function 'protectedCall'
    	.\luaunit.lua:1489: in function 'execOneFunction'
    	.\luaunit.lua:1577: in function 'runSuiteByInstances'
    	.\luaunit.lua:1641: in function 'runSuiteByNames'
    	.\luaunit.lua:1717: in function 'runSuite'
    	example_with_luaunit.lua:140: in main chunk
    	[C]: in ?
not ok 14	test2_withFailure
    example_with_luaunit.lua:130: assertion failed!
    stack traceback:
    	example_with_luaunit.lua:130: in function 'test2_withFailure'
    	.\luaunit.lua:1434: in function <.\luaunit.lua:1434>
    	[C]: in function 'xpcall'
    	.\luaunit.lua:1434: in function 'protectedCall'
    	.\luaunit.lua:1489: in function 'execOneFunction'
    	.\luaunit.lua:1577: in function 'runSuiteByInstances'
    	.\luaunit.lua:1641: in function 'runSuiteByNames'
    	.\luaunit.lua:1717: in function 'runSuite'
    	example_with_luaunit.lua:140: in main chunk
    	[C]: in ?
ok     15	test3
# Ran 15 tests in 0.000 seconds, 3 successes, 12 failures
